//users

export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS';
export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const REGISTER_FAIL ='REGISTER_FAIL';
export const LOGIN_FAIL ='LOGIN_FAIL';
export const GET_ERRORS ='GET_ERRORS';
export const CLEAR_ERRORS ='CLEAR_ERRORS';
export const USER_LOADED ='USER_LOADED';
export const USER_LOADING ='USER_LOADING';
export const AUTH_ERROR ='AUTH_ERROR';




//admin


// orders

export const GET_ORDERS ='GET_ORDERS';
export const ADD_ORDER ='ADD_ORDER';
export const DELETE_ORDER ='DELETE_ORDER';
export const ORDER_LOADING ='ORDER_LOADING';

export const UPDATE_ORDER ='UPDATE_ORDER';
export const ORDERS_SET_CURRENT ='ORDERS_SET_CURRENT';
export const ORDERS_CLEAR_CURRENT ='ORDERS_CLEAR_CURRENT';
export const CLEAR_ORDERS ='CLEAR_ORDERS';
export const ORDERS_SET_LOADING ='ORDERS_SET_LOADING';
export const ORDERS_ERROR ='ORDERS_ERROR';

// tables

export const GET_TABLES ='GET_TABLES';
export const ADD_TABLE ='ADD_TABLE';
export const DELETE_TABLE ='DELETE_TABLE';
export const UPDATE_TABLE ='UPDATE_TABLE';
export const TABLES_SET_CURRENT ='TABLES_SET_CURRENT';
export const TABLES_CLEAR_CURRENT ='TABLES_CLEAR_CURRENT';
export const CLEAR_TABLES ='CLEAR_TABLES';
export const TABLES_SET_LOADING ='TABLES_SET_LOADING';
export const TABLES_ERROR ='TABLES_ERROR';
